### ISSUE TITLE
Fails to register

### ISSUE THREAD

**Issue by shrawanzadoo** [localz/Spotz3-Android-SDK#1]
Downloaded the Spotz3 android sdk sample. Provided the *application id and application key* in the initialise method. I am using a 4.1.1(API16) device. When I run the app it fails to register and i get this stack trace :

E: getRegisterDeviceObservable onError
E: LocalzApiException{code='null', message='null', statusCode=0, superMessage=Exception while executing API request: DeviceRegisterPostApi}
E:     at com.localz.spotz.api.v1.DeviceRegisterPostApi.execute(DeviceRegisterPostApi.java:35)
E:     at com.localz.spotz.sdk.Spotz$2.run(Spotz.java:387)
E:     at rx.util.async.operators.OperatorFromFunctionals$1.call(OperatorFromFunctionals.java:52)
E:     at rx.util.async.operators.OperatorFromFunctionals$InvokeAsync.call(OperatorFromFunctionals.java:73)
E:     at rx.util.async.operators.OperatorFromFunctionals$InvokeAsync.call(OperatorFromFunctionals.java:62)
E:     at rx.Observable.unsafeSubscribe(Observable.java:7507)
E:     at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
E:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
E:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
E:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
E:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
E:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
E:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E:     at java.lang.Thread.run(Thread.java:856)
E:  Caused by: java.io.IOException: No authentication challenges found
E:     at libcore.net.http.HttpURLConnectionImpl.getAuthorizationCredentials(HttpURLConnectionImpl.java:427)
E:     at libcore.net.http.HttpURLConnectionImpl.processAuthHeader(HttpURLConnectionImpl.java:407)
E:     at libcore.net.http.HttpURLConnectionImpl.processResponseHeaders(HttpURLConnectionImpl.java:356)
E:     at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:292)
E:     at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:486)
E:     at libcore.net.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:134)
E:     at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
E:     at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:94)
E:     at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
E:     at com.localz.spotz.api.v1.DeviceRegisterPostApi.execute(DeviceRegisterPostApi.java:27)
E:     at com.localz.spotz.sdk.Spotz$2.run(Spotz.java:387) 
E:     at rx.util.async.operators.OperatorFromFunctionals$1.call(OperatorFromFunctionals.java:52) 
E:     at rx.util.async.operators.OperatorFromFunctionals$InvokeAsync.call(OperatorFromFunctionals.java:73) 
E:     at rx.util.async.operators.OperatorFromFunctionals$InvokeAsync.call(OperatorFromFunctionals.java:62) 
E:     at rx.Observable.unsafeSubscribe(Observable.java:7507) 
E:     at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62) 
E:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
E:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442) 
E:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305) 
E:     at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
E:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150) 
E:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264) 
E:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
E:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
E:     at java.lang.Thread.run(Thread.java:856) 
E: init onError

**Comment by alekseychugaev** [comment]
Hi @shrawanzadoo, 
Could provide the first 5 characters of your 'applicationId'?

**Comment by shrawanzadoo** [comment]
Hey ! "aBPLv" are the first five characters. I was able to use the same to successfully register on iOS (using the different iOS client id).

**Comment by alekseychugaev** [comment]
Hi @shrawanzadoo 
I can't seem to find any requests coming from an android device for your applicationId. Could you please confirm that you're using a key starting with 'eTa'.

**Comment by shrawanzadoo** [comment]
Hi,

Yes I am using a key starting with 'eTa'. I think there is an issue with
app not being able to connect with the registration API and hence not being
able to register. Do I need to add a certificate/security exception to
allow the app to connect ?

On Mon, Nov 9, 2015 at 1:17 AM, Aleksey Chugaev <notifications@github.com>
wrote:

> Hi @shrawanzadoo <https://github.com/shrawanzadoo>
> I can't seem to find any requests coming from an android device for your
> applicationId. Could you please confirm that you're using a key starting
> with 'eTa'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/localz/Spotz3-Android-SDK/issues/1#issuecomment-154895925>
> .
>



-- 
Regards,
Shrawan Zadoo
+44 747 88266 26

**Comment by alekseychugaev** [comment]
Hi,

No, there are no special requirements to connect to the API. Can you access https://spotz-eu-api.localz.io/healthcheck from a device using a browser or other client?

**Comment by shrawanzadoo** [comment]
I can access the URL, this is the response I can see :
{"result":"=^..^=","version":"bd6d8fd1d3aa29320dd2a0b04814c4d792a31107"}

But when the app tries to initialise i get some of the following errors
logged:
E: getRegisterDeviceObservable onError E: LocalzApiException{code='null',
message='null', statusCode=0, superMessage=Exception while executing API
request: DeviceRegisterPostApi}
E: Caused by: java.io.IOException: No authentication challenges found

and I can see these messages being repeated 4 times.

On Mon, Nov 9, 2015 at 10:30 AM, Aleksey Chugaev <notifications@github.com>
wrote:

> Hi,
>
> No, there are no special requirements to connect to the API. Can you
> access https://spotz-eu-api.localz.io/healthcheck from a device using a
> browser or other client?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/localz/Spotz3-Android-SDK/issues/1#issuecomment-155023596>
> .
>



-- 
Regards,
Shrawan Zadoo
+44 747 88266 26

**Comment by alekseychugaev** [comment]
When did you last try to run it? Could you try right now so I could find your request in logs?

**Comment by alekseychugaev** [comment]
Also, which version of the SDK are you using?

**Comment by shrawanzadoo** [comment]
It is the Spotz3-Android-SDK and in the app setting on the device it shows
the version to be "1.0.0".
Did run it a few times just now.

On Mon, Nov 9, 2015 at 11:21 AM, Aleksey Chugaev <notifications@github.com>
wrote:

> When did you last try to run it? Could you try right now so I could find
> your request in logs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/localz/Spotz3-Android-SDK/issues/1#issuecomment-155032041>
> .
>



-- 
Regards,
Shrawan Zadoo
+44 747 88266 26

**Comment by alekseychugaev** [comment]
Cool, looks like the sample app's dependencies are a bit out of date. I will update it and will push a new version first thing tomorrow morning (in about 12 hours). In the meantime, please replace this line in the build.gradle file:
compile 'com.localz.spotz.sdk:spotz-sdk-android:3.0.0@jar'
with
compile 'com.localz.spotz.sdk:spotz-sdk-android:3.0.2@jar'

Let me know if that doesn't help.

**Comment by shrawanzadoo** [comment]
Hi,
Thanks for the quick communication, really appreciate it.

The app does get registered now ! I can see it on my dashboard,
but if I start scanning it gives an exception and crashes :

E: FATAL EXCEPTION: main
E: java.lang.NoSuchMethodError: com.localz.proximity.ble.BleManager.scanOnce
E:     at com.localz.spotz.sdk.Spotz.doForegroundScanOnce(Spotz.java:879)
E:     at
com.localz.spotz.sdk.Spotz.doStartForegroundScanning(Spotz.java:855)
E:     at
com.localz.spotz.sdk.Spotz.startForegroundScanning(Spotz.java:1055)

On Mon, Nov 9, 2015 at 11:35 AM, Aleksey Chugaev <notifications@github.com>
wrote:

> Cool, looks like the sample app's dependencies are a bit out of date. I
> will update it and will push a new version first thing tomorrow morning (in
> about 12 hours). In the meantime, please replace this line in the
> build.gradle file:
> compile 'com.localz.spotz.sdk:spotz-sdk-android:3.0.0@jar'
> with
> compile 'com.localz.spotz.sdk:spotz-sdk-android:3.0.2@jar'
>
> Let me know if that doesn't help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/localz/Spotz3-Android-SDK/issues/1#issuecomment-155036519>
> .
>



-- 
Regards,
Shrawan Zadoo
+44 747 88266 26

**Comment by alekseychugaev** [comment]
One more update then, replace:
compile 'com.localz.proximity.blesmart:ble-smart-sdk-android:1.0.4@jar'
with
compile 'com.localz.proximity.blesmart:ble-smart-sdk-android:1.0.5@jar'

The README.md actually lists all the correct dependencies, it's the build.gradle file that needs to be updated.

**Comment by shrawanzadoo** [comment]
Cool ! Thanks !

This is what worked for me

compile 'com.localz.spotz.sdk:spotz-api:0.2.8'
compile 'com.localz.proximity.blesmart:ble-smart-sdk-android:1.0.5@jar'
compile 'com.localz.spotz.sdk:spotz-sdk-android:3.0.2@jar'

Also, it worked for me on device with API 19 but not on API 16, logs
"BLE is not supported or Bluetooth is not enabled".


On Mon, Nov 9, 2015 at 12:05 PM, Aleksey Chugaev <notifications@github.com>
wrote:

> One more update then, replace:
> compile 'com.localz.proximity.blesmart:ble-smart-sdk-android:1.0.4@jar'
> with
> compile 'com.localz.proximity.blesmart:ble-smart-sdk-android:1.0.5@jar'
>
> The README.md actually lists all the correct dependencies, it's the
> build.gradle file that needs to be updated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/localz/Spotz3-Android-SDK/issues/1#issuecomment-155046581>
> .
>



-- 
Regards,
Shrawan Zadoo
+44 747 88266 26

**Comment by alekseychugaev** [comment]
Great to hear that it worked for you.
BLE was only introduced by Android starting from API 18. Some older devices (selected Samsung models) may not support BLE even after upgrading to API 18.
